version: '2'
services:
  service-tomcat:
    image: tomcat
    container_name: tc
    volumes:
      - ./conf:/usr/local/tomcat/conf
      - ./webapps:/usr/local/tomcat/webapps
    ports:
      - 8080:8080
      - 8443:8443

